### ISSUE TITLE
Config is currently in the client-side config

### ISSUE THREAD

**Issue by stefanpenner** [sass-eyeglass/ember-cli-eyeglass#33] opened 2017-11-07 21:05 UTC
rather it should be in the build config. Otherwise we ship our configuration to the browser, which is wasteful.

**Comment by rwjblue** [comment] 2017-11-08 03:13
Duplicate of https://github.com/sass-eyeglass/ember-cli-eyeglass/issues/16 which has more information and a path forward.

closing...

**Closed by rwjblue** 2017-11-08 03:13 UTC
